name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_PATH: vendor/bundle
        with:
          ruby-version: 2.7
      - run: bundle install
      - name: Run Rspec tests
        run: bundle exec rake test
